# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'rxSwiftRay' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for rxSwiftRay
  pod 'RxSwift', '~> 4.0'
  

end
